# GitHubActions for testing
# read the docs: https://help.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow

name: WebUi Tests

on:
  push:
    branches:
    paths:
      - '.github/workflows/web-ui-*.yaml'
      - '.github/workflows/tests-*.yaml'
      - 'web-ui/**'
      - '!web-ui/docs/**'
      - '!web-ui/**.md'
      - '!web-ui/**.rst'
      - '!web-ui/LICENSE'
  pull_request:
    branches:
    paths:
      - '.github/workflows/web-ui-*.yaml'
      - '.github/workflows/tests-*.yaml'
      - 'web-ui/**'
      - '!web-ui/docs/**'
      - '!web-ui/**.md'
      - '!web-ui/**.rst'
      - '!web-ui/LICENSE'

defaults:
  run:
    working-directory: web-ui
env:
  project-directory: web-ui
  # reports-directory: reports

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Code
        # see https://github.com/actions/checkout
        uses: actions/checkout@v2
      # TODO: write the tests
